//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class be_CustomFields
    {
        public string CustomType { get; set; }
        public string ObjectId { get; set; }
        public System.Guid BlogId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Attribute { get; set; }
    }
}
