//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class be_Categories
    {
        public int CategoryRowID { get; set; }
        public System.Guid BlogID { get; set; }
        public System.Guid CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
    }
}
