//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class be_PackageFiles
    {
        public string PackageId { get; set; }
        public int FileOrder { get; set; }
        public string FilePath { get; set; }
        public bool IsDirectory { get; set; }
    }
}
