//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEngineEntities : DbContext
    {
        public BlogEngineEntities()
            : base("name=BlogEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<be_BlogRollItems> be_BlogRollItems { get; set; }
        public DbSet<be_Blogs> be_Blogs { get; set; }
        public DbSet<be_Categories> be_Categories { get; set; }
        public DbSet<be_DataStoreSettings> be_DataStoreSettings { get; set; }
        public DbSet<be_FileStoreDirectory> be_FileStoreDirectory { get; set; }
        public DbSet<be_FileStoreFiles> be_FileStoreFiles { get; set; }
        public DbSet<be_FileStoreFileThumbs> be_FileStoreFileThumbs { get; set; }
        public DbSet<be_PackageFiles> be_PackageFiles { get; set; }
        public DbSet<be_Packages> be_Packages { get; set; }
        public DbSet<be_Pages> be_Pages { get; set; }
        public DbSet<be_PingService> be_PingService { get; set; }
        public DbSet<be_PostCategory> be_PostCategory { get; set; }
        public DbSet<be_PostComment> be_PostComment { get; set; }
        public DbSet<be_PostNotify> be_PostNotify { get; set; }
        public DbSet<be_Posts> be_Posts { get; set; }
        public DbSet<be_PostTag> be_PostTag { get; set; }
        public DbSet<be_Profiles> be_Profiles { get; set; }
        public DbSet<be_QuickNotes> be_QuickNotes { get; set; }
        public DbSet<be_QuickSettings> be_QuickSettings { get; set; }
        public DbSet<be_Referrers> be_Referrers { get; set; }
        public DbSet<be_RightRoles> be_RightRoles { get; set; }
        public DbSet<be_Rights> be_Rights { get; set; }
        public DbSet<be_Roles> be_Roles { get; set; }
        public DbSet<be_Settings> be_Settings { get; set; }
        public DbSet<be_StopWords> be_StopWords { get; set; }
        public DbSet<be_UserRoles> be_UserRoles { get; set; }
        public DbSet<be_Users> be_Users { get; set; }
        public DbSet<be_CustomFields> be_CustomFields { get; set; }
    }
}
